swagger: "2.0"
info:
  title: User API
  description: API to manage user registration
  version: "1.0.0"
basePath: /api/v1
schemes:
  - http
produces:
  - application/json
consumes:
  - multipart/form-data

paths:
  /getRoleType:
    get:
      tags:
        - Roles
      summary: Get All Roles
      description: Get a list of role types.
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    role_type:
                      type: string
  /getAllPlans:
    get:
      tags:
        - Plans
      summary: Get All Plans
      description: Get a list of role types.
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    role_type:
                      type: string
  /getAllMembership:
    get:
      tags:
        - Memberships
      summary: Get All Membership
      description: Get a list of role types.
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    role_type:
                      type: string
  /createUser:
    post:
      tags:
        - User
      summary: Create a new user
      description: Registers a new user with provided details
      parameters:
        - in: formData
          name: email
          type: string
          required: true
        - in: formData
          name: first_name
          type: string
          required: true
        - in: formData
          name: middle_name
          type: string
        - in: formData
          name: last_name
          type: string
          required: true
        - in: formData
          name: phone_numbers
          type: array
          items:
            type: string
          required: true
        - in: formData
          name: password
          type: string
          required: true
        - in: formData
          name: role_type
          type: string
          required: true
        - in: formData
          name: avatar
          type: file
      responses:
        201:
          description: User created successfully
        400:
          description: Bad request
        500:
          description: Internal server error
