swagger: "2.0"
info:
  title: User API
  description: API to manage user registration
  version: "1.0.0"
basePath: /api/v1
schemes:
  - http
produces:
  - application/json
consumes:
  - multipart/form-data

paths:
  /createUser:
    post:
      summary: Create a new user
      description: Registers a new user with provided details
      parameters:
        - in: formData
          name: email
          type: string
          required: true
        - in: formData
          name: first_name
          type: string
          required: true
        - in: formData
          name: middle_name
          type: string
        - in: formData
          name: last_name
          type: string
          required: true
        - in: formData
          name: phone_numbers
          type: array
          items:
            type: string
          required: true
        - in: formData
          name: password
          type: string
          required: true
        - in: formData
          name: role_type
          type: string
          required: true
        - in: formData
          name: avatar
          type: file
      responses:
        201:
          description: User created successfully
          schema:
            $ref: "#/definitions/User"
        400:
          description: Bad request
        500:
          description: Internal server error
definitions:
  User:
    type: object
    properties:
      id:
        type: string
      email:
        type: string
      first_name:
        type: string
      middle_name:
        type: string
      last_name:
        type: string
      phone_numbers:
        type: array
        items:
          type: string
      role_type:
        type: object
        properties:
          id:
            type: string
          role_type:
            type: string
